/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Roobert PRO"', '"Noto Sans"', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        display: ['"Roobert PRO"', '"Noto Sans"', 'sans-serif'],
      },
      fontSize: {
        'hero':    ['80px', { lineHeight: '1.05', letterSpacing: '-2px', fontWeight: '500' }],
        'disp-lg': ['60px', { lineHeight: '1.10', letterSpacing: '-1.5px', fontWeight: '500' }],
        'h1':      ['48px', { lineHeight: '1.15', letterSpacing: '-1px', fontWeight: '500' }],
        'h2':      ['36px', { lineHeight: '1.20', letterSpacing: '-0.5px', fontWeight: '500' }],
        'h3':      ['28px', { lineHeight: '1.25', letterSpacing: '0', fontWeight: '500' }],
        'h4':      ['22px', { lineHeight: '1.30', letterSpacing: '0', fontWeight: '500' }],
        'h5':      ['18px', { lineHeight: '1.40', letterSpacing: '0', fontWeight: '500' }],
        'subtitle':['18px', { lineHeight: '1.50', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.50', letterSpacing: '0', fontWeight: '400' }],
        'body-md-medium': ['16px', { lineHeight: '1.50', letterSpacing: '0', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '1.50', letterSpacing: '0', fontWeight: '400' }],
        'body-sm-medium': ['14px', { lineHeight: '1.50', letterSpacing: '0', fontWeight: '500' }],
        'caption': ['13px', { lineHeight: '1.40', letterSpacing: '0', fontWeight: '400' }],
        'caption-bold': ['13px', { lineHeight: '1.40', letterSpacing: '0', fontWeight: '600' }],
        'micro':   ['12px', { lineHeight: '1.40', letterSpacing: '0', fontWeight: '500' }],
        'micro-up':['11px', { lineHeight: '1.40', letterSpacing: '0.5px', fontWeight: '600' }],
        'btn':     ['14px', { lineHeight: '1.30', letterSpacing: '0', fontWeight: '500' }],
        'stat':    ['64px', { lineHeight: '1.10', letterSpacing: '-1.5px', fontWeight: '500' }],
      },
      colors: {
        // Brand & Accent
        'brand-yellow':      '#FFD02F',
        'brand-yellow-deep': '#E5B800',
        'yellow-light':      '#FFF8E1',
        'yellow-dark':       '#5C4B00',
        'brand-blue':        '#2B6BF3',
        'blue-pressed':      '#1A4FCC',
        'brand-coral':       '#F27E63',
        'coral-light':       '#FFF0ED',
        'coral-dark':        '#7A1F0A',
        'brand-rose':        '#F5B5C8',
        'brand-teal':        '#0CA789',
        'teal-light':        '#E8F8F4',
        'moss-dark':         '#0B5E4A',
        'brand-pink':        '#FDE8F0',
        'brand-orange-light':'#FFF3E6',
        'brand-red':         '#FEE2E2',
        'brand-red-dark':    '#DC2626',
        // Surface
        'canvas':            '#FFFFFF',
        'surface':           '#F7F8FA',
        'surface-soft':      '#FAFBFC',
        'surface-yellow':    '#FFF8E1',
        'surface-pricing':   '#F0EEFF',
        // Hairline
        'hairline':          '#E6E6E6',
        'hairline-soft':     '#F0F0F0',
        'hairline-strong':   '#D4D4D4',
        // Text
        'ink-deep':          '#050038',
        'ink':               '#050038',
        'charcoal':          '#37352F',
        'slate':             '#6B6F76',
        'steel':             '#8B8E94',
        'stone':             '#A3A6AC',
        'muted':             '#C4C7CC',
        'on-dark':           '#FFFFFF',
        'on-dark-muted':     'rgba(255,255,255,0.60)',
        // Footer
        'footer-bg':         '#050038',
        // Semantic
        'success':           '#0CA789',
        'danger':            '#E5484D',
        'warning':           '#F5A623',
        'info':              '#2B6BF3',
      },
      borderRadius: {
        'pill': '9999px',
      },
    },
  },
  plugins: [],
}
